// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPC3kGbLlUbgRkhKO7yG8rluE21QWsdpU',
    appId: '1:830177900227:web:d8fb19d7b07f370a941476',
    messagingSenderId: '830177900227',
    projectId: 'campus-trade1',
    authDomain: 'campus-trade1.firebaseapp.com',
    storageBucket: 'campus-trade1.firebasestorage.app',
    measurementId: 'G-HXMK6QTVN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFLlgzAV9XVt4mGwqR6sNg9nr34x_oz9c',
    appId: '1:830177900227:android:32a21776f56b8003941476',
    messagingSenderId: '830177900227',
    projectId: 'campus-trade1',
    storageBucket: 'campus-trade1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeueny1nCvkKtvtJPzDBNCgJC4PzQwQPA',
    appId: '1:830177900227:ios:4d81a2699345e395941476',
    messagingSenderId: '830177900227',
    projectId: 'campus-trade1',
    storageBucket: 'campus-trade1.firebasestorage.app',
    iosBundleId: 'com.example.depi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeueny1nCvkKtvtJPzDBNCgJC4PzQwQPA',
    appId: '1:830177900227:ios:4d81a2699345e395941476',
    messagingSenderId: '830177900227',
    projectId: 'campus-trade1',
    storageBucket: 'campus-trade1.firebasestorage.app',
    iosBundleId: 'com.example.depi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPC3kGbLlUbgRkhKO7yG8rluE21QWsdpU',
    appId: '1:830177900227:web:56c364895bc38524941476',
    messagingSenderId: '830177900227',
    projectId: 'campus-trade1',
    authDomain: 'campus-trade1.firebaseapp.com',
    storageBucket: 'campus-trade1.firebasestorage.app',
    measurementId: 'G-097V6DLPXM',
  );

}